#!/bin/bash
#!/bin/sh

mkdir sol0

blockMesh
solver=scalarTransportFoam

$solver | tee log0
postProcess -func sampleDict -latestTime
cp postProcessing/sampleDict/5/line_centreProfile_T.xy sol0/line_centreProfile_T.xy.0

./p1


#------------------------------------------------------------------------------ 
